name: Codeforces Contest Scraper

on:
  push:
    branches:
      - master
  # Runs cron job
  schedule:
    - cron: '00 */8 * * *'
jobs:
  scrape_contests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt

      - name: Run script
        run: python3 .github/json-extractor.py

      - name: List files in current directory
        run: ls -la

      - name: Commit and push contests.json
        run: |
          git config user.name "SeonghoLee"
          git config user.email "SeonghoLee4@gmail.com"
          git add .github/contests.json
          git commit -m "new contests.json added"
          git push